version: '3'
services:
  
 
  mysql:
    image: mysql:5.6
    container_name: mysql
    hostname: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf/default.cnf:/etc/mysql/conf.d/default.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LC_ALL=C.UTF-8

  
